CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`company` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`position` varchar(255),
	`brand` varchar(100) NOT NULL,
	`equipmentType` varchar(100) NOT NULL,
	`model` varchar(100) NOT NULL,
	`serialNumber` varchar(100),
	`hoursOperation` varchar(50),
	`selectedServices` json NOT NULL,
	`problemDescription` text NOT NULL,
	`urgency` enum('normal','priority','urgent','emergency') NOT NULL DEFAULT 'normal',
	`location` varchar(255) NOT NULL,
	`preferredDate` varchar(50),
	`additionalNotes` text,
	`images` json,
	`status` enum('pending','reviewing','quoted','accepted','rejected','completed') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`quotedPrice` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`)
);
