CREATE TABLE `costParameters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`unitCost` int NOT NULL,
	`unit` varchar(50) NOT NULL,
	`supplier` varchar(255),
	`isActive` enum('yes','no') NOT NULL DEFAULT 'yes',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `costParameters_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `generatedQuotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quotationNumber` varchar(50) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientRut` varchar(20),
	`clientAddress` varchar(500),
	`clientCity` varchar(100),
	`clientContact` varchar(255),
	`clientPhone` varchar(50),
	`clientEmail` varchar(320),
	`equipmentType` varchar(100) NOT NULL,
	`equipmentBrand` varchar(100) NOT NULL,
	`equipmentModel` varchar(100) NOT NULL,
	`equipmentSerial` varchar(100),
	`equipmentCapacity` varchar(50),
	`equipmentLocation` varchar(255),
	`serviceType` enum('repair','shielding','reconstruction') NOT NULL,
	`durationDays` int NOT NULL,
	`materialsProvider` enum('forgemine','client') NOT NULL DEFAULT 'forgemine',
	`equipmentProvider` enum('forgemine','client') NOT NULL DEFAULT 'forgemine',
	`operationalProvider` enum('forgemine','client') NOT NULL DEFAULT 'forgemine',
	`laborCost` int NOT NULL,
	`materialsCost` int NOT NULL,
	`equipmentCost` int NOT NULL,
	`operationalCost` int NOT NULL,
	`subtotalCost` int NOT NULL,
	`profitMargin` int NOT NULL,
	`profitAmount` int NOT NULL,
	`netPrice` int NOT NULL,
	`ivaAmount` int NOT NULL,
	`totalPrice` int NOT NULL,
	`costBreakdown` json,
	`validityDays` int NOT NULL DEFAULT 30,
	`paymentTerms` varchar(255) NOT NULL DEFAULT '50% anticipo / 50% entrega',
	`warrantyTerms` varchar(255),
	`additionalNotes` text,
	`status` enum('draft','sent','accepted','rejected','expired') NOT NULL DEFAULT 'draft',
	`pdfUrl` varchar(500),
	`linkedQuoteId` int,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`sentAt` timestamp,
	CONSTRAINT `generatedQuotations_id` PRIMARY KEY(`id`),
	CONSTRAINT `generatedQuotations_quotationNumber_unique` UNIQUE(`quotationNumber`)
);
